### ISSUE TITLE
Update install script to run on ubuntu20!

### ISSUE THREAD

**Issue by arduino12** [netanelf/bicycle_video_player#10]
**Hi!**

I made a new script to run on new NUC with ubuntu20 - so please replace the old script with this:

```
#!/bin/bash

if (( EUID == 0 )); then
	echo 'Please run without sudo!' 1>&2
	exit 1
fi

cd "$(dirname "${BASH_SOURCE[0]}")"

sudo apt update
sudo apt install -y git python2 vlc htop

wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo python2

pip2 install numpy pyserial opencv-python==3.4.8.29 # ==3.4.0.14

cd ~
git clone https://github.com/netanelf/bicycle_video_player.git
cd ~/bicycle_video_player
chmod +x achbar.sh
mkdir -p ~/.config/autostart/
cp run_race_player.desktop ~/.config/autostart/

sudo usermod -a -G dialout $USER

echo "Installation completed. Restarting in 1 minute"
shutdown -r -t 1
```

**Thanks!**

**Comment by netanelf** [comment]
Hi,
Of course!
1. i will insert the script to the repository
2. if you need more changes/ adaptions etc. - i am more than happy to help
3. if you want RW permissions on the repository tell me.

**Comment by amirbs** [comment]
הי נתנאל
תוכל לעדכן אותנו אחרי שתעדכן את הסקריפט ?
יש אפשרות לתת ארד הרשאה לעשות שינויים כאלו בעתיד(הוא זה שכרגע מטפל בכל המוצגים הממוחשבים  בתערוכת אופניים).
לחילופין האם כדאי להעביר את כל הקוד לגיט של המוזיאון עם גישה של דימה (נדמה לי שמה שיש לנו הוא אפילו בתשלום במעט בלי מגבלת נפח).
ארד, נתנאל , האם צריך במקביל לשינוי הסקריפט בגיט לשנות משהו במה שכתוב בספר הטכני של ההתקנה (עמוד 80 )
Requirements for Linux environment
The easiest way to install the software (this method also makes sure that the correct version is installed) is to run the following at the terminal of the installed computer (one line):
wget -O install_script https://raw.githubusercontent.com/netanelf/bicycle_video_player/master/install.sh && source install_script

ו\או בהמשך המתייחס למניעת כיבוי מסך וכולי
Preventing the screen from switching off
When using two NUC PCs in the museum, a fault was detected. The screen is switched off after 15 minutes. Although usually in Linux, the automatic screen turnoff can be cancelled, the problem was not solved, probably due to incompatibility between the NUC PC and the Linux. In order to bypass the problem, the solution was to use a script that moves the mouse every few seconds to prevent the screen from turning off.
In future use with another PC perhaps this solution will not be necessary. It is worth checking.
This part describes the manual installation to meet the preliminary requirements without using the auxiliary file:
Preliminary requirements.
 sudo apt-get install vlc -y
 sudo apt-get install git -y
 sudo apt-get install python-numpy -y
 sudo apt-get install python-opencv -y
 sudo apt-get install python-serial -y
 sudo usermod -a -G dialout $USER
 Installation of the software
 cd ~/
 git clone https://github.com/netanelf/bicycle_video_player
 cd ~/bicycle_video_player
 Using the mouse moving script
 chmod +x achbar.sh
 Automatic start of the software when the PC is switched on
 mkdir ~/.config
 mkdir ~/.config/autostart
 cp run_race_player.desktop ~/.config/autostart


אם כ - צריך לזכור זאת יחד עם שאר העדכונים של הספר (רוני ?)
המון תודה
אמיר ב


________________________________
מאת: arduino12 <notifications@github.com>
‏‏נשלח: יום רביעי 21 אוקטובר 2020 20:16
‏‏אל: netanelf/bicycle_video_player <bicycle_video_player@noreply.github.com>
עותק: Subscribed <subscribed@noreply.github.com>
‏‏נושא: [netanelf/bicycle_video_player] Update install script to run on ubuntu20! (#10)


Hi!

I made a new script to run on new NUC with ubuntu20 - so please replace the old script with this:

#!/bin/bash

if (( EUID == 0 )); then
        echo 'Please run without sudo!' 1>&2
        exit 1
fi

cd "$(dirname "${BASH_SOURCE[0]}")"

sudo apt update
sudo apt install -y git python2 vlc htop

wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo python2

pip2 install numpy pyserial opencv-python==3.4.8.29 # ==3.4.0.14

cd ~
git clone https://github.com/netanelf/bicycle_video_player.git
cd ~/bicycle_video_player
chmod +x achbar.sh
mkdir -p ~/.config/autostart/
cp run_race_player.desktop ~/.config/autostart/

sudo usermod -a -G dialout $USER

echo "Installation completed. Restarting in 1 minute"
shutdown -r -t 1


Thanks!

**Comment by amirbs** [comment]
אופס, אני רואה שכיוונתי לדעת גדולים ונתנאל כבר מטפל בנושא.
רק עדכנו בסוף את רוני לגבי אם צריך לשנות משהו בספר התחזוקה ואם יש דברים שדימה צריך לטפל בהם

המון תודה
אמיר ב

________________________________
מאת: netanelf <notifications@github.com>
‏‏נשלח: יום רביעי 21 אוקטובר 2020 21:23
‏‏אל: netanelf/bicycle_video_player <bicycle_video_player@noreply.github.com>
עותק: Subscribed <subscribed@noreply.github.com>
‏‏נושא: Re: [netanelf/bicycle_video_player] Update install script to run on ubuntu20! (#10)


Hi,
Of course!

  1.  i will insert the script to the repository
  2.  if you need more changes/ adaptions etc. - i am more than happy to help
  3.  if you want RW permissions on the repository tell me.

**Comment by amirbs** [comment]
הי אמיר!

בדיוק ביצעתי את השינוי שארד ביקש (וגם שאלתי אם הוא רוצה גישה/ עזרה אם צריך).
מבחינתי אין בעיה שהקוד ישאר תחת החשבון שלי:
1. אך זה אומר שהקוד הוא קוד פתוח שכל העולם יכול לראות (אני לא רואה בזה
בעיה- אלא אפילו משהו חיובי)
2. אתן למי שרוצה הרשאות כתיבה (נותן עכשיו לארד)

ובלי קשר אם צריך עזרה עם הקוד הזה/ שיפורים וכו אני זמין!

מקווה שהכל הולך בסדר במוזיאון
נתנאל

**Comment by amirbs** [comment]
הי נתנאל
אין בכלל בעיה שהקוד יהיה פתוח, אם לך אין בעיה ש"יבזבז\יעלה" לך נפח איחסון, בכל מקרה כדאי מדי פעם לגבות ובהחלט רצוי שלארד תהיה הרשאה (למקרה שלא תהיה זמין).

מה שאני רק רוצה לוודא זה את עניין השינוי (אם צריך) בספר התחזוקה למקרה שנצטרך לתת הנחיות לאנשים במוזיאון אחר להתקין על נוק חדש (או שתהיה להם תקלה ולא יצליחו להשיג אותנו).  מה שכתבתי במיילים הקודמים.
בכל מקרה אנחנו צריכים כנראה לעדכן כמה דברים בספר.

חוצמזה המוזיאון סגור לקהל, נפתחנו לשבועיים בסוף החופש הגדול, אחרי הרבה מאבקים ובמגבלות של רישום מראש, מספר מוגבל של מבקרים ועוד אילוצי "תו סגול", אבל מראש השנה נסגרנו שוב, בתקווה שתוך כמה שבועות נוכנס גם למתווה החזרה.
מבחינת עבודת צוות יש חלוקה לקפסולות כי יש לנו משימות אחרות לעשות, תחזוקת והמשך פיתוח מוצגים ללקראת פתיחה, מעבר להוראה מקוונת, גם של המוזיאון עצמו לתלמידים וכיתות וגם שרותים שאנחנו נותנים לגופיים חינוכיים אחרים, הכנת ערכות ללימוד עצמי והיברידי ועוד. כך שהחשש הכי גדול הוא שמישהו מהצוות ייחלה וישבית את כולנו לשבועיים (קרה בסוכות אבל במזל ממילא היינו כולנו בחופש).
אנחנו (בעיקר ארד) גם מנסים להשמיש מחדש את קיר ה"לא הכל לד" (אבל עם  אספרסיב ESP32 שכנראה יכול להחליף את הפאי). יש קצת הבעיות של רעשים\הפרעות\חוסר שליטה\סנכרון (שכאולי קשורים למצמדים האופטיים, אם אני זוכר נכון גם אצלכם היו בעיות כאלו ובסוף וויתרתם עליהם)
אבל מאמין שנסתדר בסוף.
נעדכן אתכם בכל מקרה
ויותר חשוב, מעבדת מייק הורחבה והשתכללה משמעותית בשנתיים האחרונות, בפרט רכשנו  CNC לעץ לפלטה שלמה !!.  אם אתה (או זוגתך...) תרצו לחתוך\לעצב משהו מעץ - דבר עם  איל או אורי קאופמן (אעביר לך את הפרטים שלהם) שמפעילים אותה.

להתראות ורק בריאות
אמיר ב
0542406559


________________________________
מאת: Netanel Freiman <netanelf@gmail.com>
‏‏נשלח: יום רביעי 21 אוקטובר 2020 21:31
‏‏אל: Amir Ben. Shalom <amirb@mada.org.il>
עותק: netanelf/bicycle_video_player <bicycle_video_player@noreply.github.com>; netanelf/bicycle_video_player <reply@reply.github.com>; Arad Eizen <arad.rgb@gmail.com>; Rony Ben-Chaim <Ronybc@mada.org.il>; Dmitry Polonsky <Dmitryp@mada.org.il>; Subscribed <subscribed@noreply.github.com>
‏‏נושא: Re: ‏ [netanelf/bicycle_video_player] Update install script to run on ubuntu20! (#10)

הי אמיר!

בדיוק ביצעתי את השינוי שארד ביקש (וגם שאלתי אם הוא רוצה גישה/ עזרה אם צריך).
מבחינתי אין בעיה שהקוד ישאר תחת החשבון שלי:
1. אך זה אומר שהקוד הוא קוד פתוח שכל העולם יכול לראות (אני לא רואה בזה בעיה- אלא אפילו משהו חיובי)
2. אתן למי שרוצה הרשאות כתיבה (נותן עכשיו לארד)

ובלי קשר אם צריך עזרה עם הקוד הזה/ שיפורים וכו אני זמין!

מקווה שהכל הולך בסדר במוזיאון
נתנאל

On Wed, Oct 21, 2020 at 9:26 PM Amir Ben. Shalom <amirb@mada.org.il<mailto:amirb@mada.org.il>> wrote:
הי נתנאל
תוכל לעדכן אותנו אחרי שתעדכן את הסקריפט ?
יש אפשרות לתת ארד הרשאה לעשות שינויים כאלו בעתיד(הוא זה שכרגע מטפל בכל המוצגים הממוחשבים  בתערוכת אופניים).
לחילופין האם כדאי להעביר את כל הקוד לגיט של המוזיאון עם גישה של דימה (נדמה לי שמה שיש לנו הוא אפילו בתשלום במעט בלי מגבלת נפח).
ארד, נתנאל , האם צריך במקביל לשינוי הסקריפט בגיט לשנות משהו במה שכתוב בספר הטכני של ההתקנה (עמוד 80 )
Requirements for Linux environment
The easiest way to install the software (this method also makes sure that the correct version is installed) is to run the following at the terminal of the installed computer (one line):
wget -O install_script https://raw.githubusercontent.com/netanelf/bicycle_video_player/master/install.sh && source install_script

ו\או בהמשך המתייחס למניעת כיבוי מסך וכולי
Preventing the screen from switching off
When using two NUC PCs in the museum, a fault was detected. The screen is switched off after 15 minutes. Although usually in Linux, the automatic screen turnoff can be cancelled, the problem was not solved, probably due to incompatibility between the NUC PC and the Linux. In order to bypass the problem, the solution was to use a script that moves the mouse every few seconds to prevent the screen from turning off.
In future use with another PC perhaps this solution will not be necessary. It is worth checking.
This part describes the manual installation to meet the preliminary requirements without using the auxiliary file:
Preliminary requirements.
 sudo apt-get install vlc -y
 sudo apt-get install git -y
 sudo apt-get install python-numpy -y
 sudo apt-get install python-opencv -y
 sudo apt-get install python-serial -y
 sudo usermod -a -G dialout $USER
 Installation of the software
 cd ~/
 git clone https://github.com/netanelf/bicycle_video_player
 cd ~/bicycle_video_player
 Using the mouse moving script
 chmod +x achbar.sh
 Automatic start of the software when the PC is switched on
 mkdir ~/.config
 mkdir ~/.config/autostart
 cp run_race_player.desktop ~/.config/autostart


אם כ - צריך לזכור זאת יחד עם שאר העדכונים של הספר (רוני ?)
המון תודה
אמיר ב


________________________________
מאת: arduino12 <notifications@github.com<mailto:notifications@github.com>>
‏‏נשלח: יום רביעי 21 אוקטובר 2020 20:16
‏‏אל: netanelf/bicycle_video_player <bicycle_video_player@noreply.github.com<mailto:bicycle_video_player@noreply.github.com>>
עותק: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
‏‏נושא: [netanelf/bicycle_video_player] Update install script to run on ubuntu20! (#10)


Hi!

I made a new script to run on new NUC with ubuntu20 - so please replace the old script with this:

#!/bin/bash

if (( EUID == 0 )); then
        echo 'Please run without sudo!' 1>&2
        exit 1
fi

cd "$(dirname "${BASH_SOURCE[0]}")"

sudo apt update
sudo apt install -y git python2 vlc htop

wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo python2

pip2 install numpy pyserial opencv-python==3.4.8.29 # ==3.4.0.14

cd ~
git clone https://github.com/netanelf/bicycle_video_player.git
cd ~/bicycle_video_player
chmod +x achbar.sh
mkdir -p ~/.config/autostart/
cp run_race_player.desktop ~/.config/autostart/

sudo usermod -a -G dialout $USER

echo "Installation completed. Restarting in 1 minute"
shutdown -r -t 1


Thanks!

**Comment by arduino12** [comment]
Fixed in 90c10e69ec24ccf159168a6a5d0ae2e8c67e2352 !
